//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booking_rdms_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public Nullable<int> clubid { get; set; }
        public int memberid { get; set; }
        public string streetname { get; set; }
        public string number { get; set; }
        public string site { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
