//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booking_rdms_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPicture
    {
        public int pictureid { get; set; }
        public Nullable<int> memberid { get; set; }
        public string pic_url { get; set; }
        public string pic_min { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
